# Generated by Django 5.0.1 on 2024-01-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name_plural': 'Natijalar'},
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name_plural': 'Avzalliklar'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Murojaatlar'},
        ),
        migrations.AlterModelOptions(
            name='praise',
            options={'verbose_name_plural': 'Yutuqlar'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='technicians',
            options={'verbose_name_plural': 'Texnik xodimlar'},
        ),
    ]
