# Generated by Django 5.0.1 on 2024-01-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_delete_booking_alter_achievements_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievements',
        ),
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.DeleteModel(
            name='Praise',
        ),
    ]
