# Generated by Django 5.0.1 on 2024-01-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_achievements_delete_advantage_delete_praise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('select', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Scroll',
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Fikrlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Murojaatlar'},
        ),
    ]
