# Generated by Django 5.0.1 on 2024-01-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_delete_scroll_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='caption',
        ),
    ]
