# Generated by Django 5.0.1 on 2024-01-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_services_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
    ]
