# Generated by Django 5.0.1 on 2024-01-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='select',
            field=models.CharField(max_length=255),
        ),
    ]
